spring:
  cloud:
    gateway:
      routes:
        - id: a-service22
          uri: http://localhost:8089
          predicates:
            - Path=/aservice/**
          filters:
            - RewritePath=/aservice/?(?<segment>.*), /oma/$\{segment}
        - id: b-service
          uri: http://httpbin.org:80
          predicates:
            - Path=/bservice/**
          filters:
            - RewritePath=/bservice/?(?<segment>.*), /anything/$\{segment}
        - id: httpbin_json
          uri: https://httpbin.org/
          predicates:
            - Path=/get
          metadata:
            connection-timeout: '300'
            response-timeout: '300'
